### ISSUE TITLE
DynamicRouting not working after deployment

### ISSUE THREAD

**Issue by dipendermohan-surfcode** [KenticoDevTrev/DynamicRouting#10]
Hello Trev,

Hope you doing well !!

Thanks for the wonderful module !!
**Description**:-
We installed the package on my DEV machine and refresh the site and it worked, we took the code to my staging server and did the refresh but was not able to see the DynamicRouting module.

We import the DynamicRouting from Dev site to staging and DynamicRouting module created in module application in cms desk but the "Classes" in Classtab missing.

Please suggest us how we can get it working on staging.

Thanks in advance.
Thanks
Dipender

**Comment by KenticoDevTrev** [comment]
Most likely you pushed the dynamic routing files to your staging, but the
module is database so you either need to use the site-> export site or
object, select only the dynamic routing module and import it on staging, or
run the nuget package against the staging site or database.

This is something you'll encounter with any module. I also have a blog
article on how to enable staging tracking of module classes on devtrev.com
but it may not help you now, just got the future.

**Comment by KenticoDevTrev** [comment]
Now that i'm on a desktop instead of phone, try these steps and please tell me if that works now!

I believe you have 2 options:

INSTALL NUGET PACKAGE ON OTHER ENVIRONMENTS
the best option is to simply install the Dynamic Routing nuget package on each environment individually, and run the instance.  This will properly add in the files and install the module.

INSTALL NUGET PACKAGE ON ONE, FILES PUSHED THROUGH REPOSITORIES, MODULE INSTALL ONLY
If you are pushing your bin dlls manually, and you only need the Module itself (the database classes and tables, etc), then follow these steps:

1: Go to Dev instance Admin
2: Go to Sites -> Export
3: "Do not preselect any object" and Next
4: Check "Export TaskS" "Export Files" "Export custom assembly files" on the export settings
5: Go to Development -> Modules, and find and check "Dynamic Routing", hit Next
6: Save the file.
7: Go to Staging instance admin
8: Go to Sites -> Import site or objects
9: Select your file from step 6, hit Next
10: For Import Settings, check "Import Tasks", "Import Files", "Import code files" "Import custom assembly files"
11: hit next until installed.

Note this will NOT include the two dll's in the bin folder, use your code repository for that.


Please tell me which one you did and how you resolved, i'll update documentation.

**Comment by dipendermohan-surfcode** [comment]
Hello Trev,

Thanks for the quick reply.
I got it resolved by importing the "DynamicRouting.Kentico_12.29.3.zip" manually in the staging site.

"DynamicRouting.Kentico.12.29.3\content\App_Data\CMSModules\DynamicRouting.Kentico\Install"
I guess it cretaed all required objects.

Thanks
Dipender
![image](https://user-images.githubusercontent.com/13732734/69647890-4cea9b00-1090-11ea-930d-1126f285cd89.png)

[DynamicRouting.Kentico_12.29.3.zip](https://github.com/KenticoDevTrev/DynamicRouting/files/3892604/DynamicRouting.Kentico_12.29.3.zip)
